# .github/FUNDING.yml

github: [NeoNovaLabs]
custom: 
  - "https://linktr.ee/NeoNovaLabsYT"
  - "bitcoin:1LnApJ6XnTgHb8Y3mbzq4NSCMgFv5t7P18"
  - "ethereum:0x922fB8cf83608B101E2B881f0C3FB3F25d2906Ec"
  - "verus:RV4MtoypPHUrf8uFEmyx9tmQ7wiWkbbzBW"
